---
title: IRMA
author: Privacy by Design Foundation
email: ''
description: Met IRMA heb je in de hand wat er met jouw gegevens gebeurt.
baseurl: "/"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
markdown: kramdown
gems:
- jekyll-feed
- jekyll-menus
