---
title: IRMA
author: Privacy by Design Foundation
email: ''
description: IRMA is an authentication app that protects your privacy.
baseurl: "/"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
markdown: kramdown
gems:
- jekyll-feed
- jekyll-menus
